services:
  - type: web
    name: bondenifarm
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bondenifarm-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: bondenifarm-db
    plan: free
    databaseName: bondenifarm
    user: bondenifarm
